apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wintest-nano
  name: wintest-nano
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wintest-nano
  template:
    metadata:
      labels:
        app: wintest-nano
      name: wintest-nano
    spec:
     containers:
      - name: wintest-nano
        image: mcr.microsoft.com/dotnet/samples:aspnetapp-nanoserver-1809
        # command:
        # - "cmd /c ping -t localhost > NUL"
     nodeSelector:
      kubernetes.io/os: windows