apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wintest-core
  name: wintest-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wintest-core
  template:
    metadata:
      labels:
        app: wintest-core
      name: wintest-core
    spec:
     containers:
      - name: wintest-core
        image: mcr.microsoft.com/windows/servercore:10.0.17763.1879
        command:
        - powershell.exe
        - -command
        - "echo 'Testing...'; ping -t localhost"
     nodeSelector:
      kubernetes.io/os: windows