apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tztest
  name: tztest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tztest
  template:
    metadata:
      labels:
        app: tztest
      name: tztest
    spec:
     containers:
      - name: tztest
        image: cdwms.azurecr.io/wintestcoretz:10.0.17763.1935
        imagePullPolicy: Always
        command:
        - powershell.exe
        - -command
        - "echo 'Testing...'; ping -t localhost"
     nodeSelector:
      kubernetes.io/os: windows